version: '3'


services:
    app:
      build: .
      container_name: app
      command: bash docker-entrypoint.sh
      volumes:
        - .:/home/django/app
      ports:
        - "8002:8002"
      depends_on:
        - db

    db:
      image: postgres
      container_name: magalu-db
      tty:  true
      environment:
        - POSTGRES_DB=magalu
        - POSRGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      volumes:
        - magalu:/var/lib/postgresql/data
    
volumes:
  magalu:
    external: true
  